'use strict';

const CONFIG = {
  WHATSAPP_NUMBER:         '573001234567',
  CAROUSEL_INTERVAL_MS:    5500,
  BACK_TOP_THRESHOLD_PX:   300,
  NAV_SCROLL_THRESHOLD_PX: 50,
  REVEAL_THRESHOLD:        0.1,
  STORAGE_KEY:             'lumiere_lang',
  DEFAULT_LANG:            'es',
};

const TRANSLATIONS = {
  es: {
    nav_servicios:  'Servicios',
    nav_nosotras:   'Nosotras',
    nav_equipo:     'Equipo',
    nav_opiniones:  'Opiniones',
    nav_galeria:    'Galería',
    nav_cta:        'Reservar',

    hero_eyebrow:    'Salón de Belleza Premium · Medellín',
    hero_title_1:    'Tu belleza,',
    hero_title_2:    'nuestra pasión',
    hero_sub:        'Un espacio íntimo donde cada visita es un ritual. Venís como clienta, salís sintiéndote la mejor versión de vos misma.',
    hero_badge:      'Disponible hoy',
    hero_float_main: '4.9 en Google',
    hero_float_sub:  '+400 reseñas',
    cta_reservar:    'Reservar ahora',
    cta_servicios:   'Ver servicios',

    trust_1_bold: '4.9★ en Google',
    trust_2:      '4.000+ clientas felices',
    trust_3:      '6 años en Medellín',
    trust_4:      'Productos libres de crueldad',

    services_label:   'Nuestros servicios',
    services_title_1: 'Lo que hacemos',
    services_title_2: 'para vos',
    services_desc:    'Cada servicio está diseñado con cuidado, usando los mejores productos y las técnicas más actuales.',

    s1_name:  'Corte y Estilizado',
    s1_price: '$45.000 – $80.000 COP',
    s1_desc:  'Corte personalizado según tu rostro y estilo, con secado y estilizado profesional incluido.',
    s2_name:  'Coloración y Mechas',
    s2_price: '$120.000 – $250.000 COP',
    s2_desc:  'Coloración completa, balayage, mechas y técnicas de color que se adaptan perfectamente a tu cabello.',
    s3_name:  'Tratamientos Capilares',
    s3_price: '$60.000 – $150.000 COP',
    s3_desc:  'Keratina, hidratación profunda y nutrición capilar para un cabello suave, brillante y saludable.',
    s4_name:  'Manicure y Pedicure',
    s4_price: '$35.000 – $65.000 COP',
    s4_desc:  'Cuidado completo de manos y pies con esmaltes semipermanentes, nail art y spa de uñas.',
    s5_name:  'Maquillaje Profesional',
    s5_price: '$80.000 – $120.000 COP',
    s5_desc:  'Maquillaje social, de noche o para eventos especiales. Natural o glamuroso, según lo que necesités.',
    s6_name:  'Cejas y Pestañas',
    s6_price: '$40.000 – $70.000 COP',
    s6_desc:  'Diseño y depilación de cejas, laminado, tinte y extensión de pestañas para una mirada perfecta.',
    service_book: 'Reservar →',

    ritual_1: 'Cada visita es un momento tuyo',
    ritual_2: 'Porque merecés sentirte increíble cada día',

    why_label:   '¿Por qué Lumière?',
    why_title_1: 'Más que un salón,',
    why_title_2: 'una experiencia',
    why1_title:  'Consulta personalizada',
    why1_desc:   'Antes de cualquier servicio, conversamos sobre lo que querés y lo que mejor le va a tu cabello, piel o estilo.',
    why2_title:  'Productos premium',
    why2_desc:   'Solo usamos marcas de alta gama, libres de crueldad y con ingredientes que realmente cuidan tu cabello y piel.',
    why3_title:  'Ambiente íntimo y relajado',
    why3_desc:   'Nuestro espacio fue diseñado para que te sientas en casa: tranquila, cómoda y completamente en paz.',

    team_label:   'Conocé al equipo',
    team_title_1: 'Las artistas',
    team_title_2: 'detrás de tu look',
    team_desc:    'Mujeres apasionadas, expertas en su arte y con ganas de hacer que cada clienta salga feliz.',
    t1_role: 'Colorista & Estilista Jefe',
    t1_exp:  '10 años de experiencia · Certificada en París',
    t2_role: 'Especialista en Tratamientos',
    t2_exp:  '7 años de experiencia · Experta en queratina',
    t3_role: 'Nail Artist & Maquilladora',
    t3_exp:  '5 años de experiencia · Especialista en nail art',

    testi_label:   'Lo que dicen ellas',
    testi_title_1: 'Clientas que',
    testi_title_2: 'volvieron a brillar',
    t1_text:    '"Valentina me hizo el balayage más lindo que he visto en mi vida. Le conté exactamente lo que quería y me entendió al tiro. El ambiente del salón es súper acogedor, nada intimidante. ¡Definitivamente vuelvo!"',
    t1_service: 'Coloración y Mechas',
    t2_text:    '"Llevaba meses con el cabello destruido por el calor. Daniela me hizo una hidratación profunda y quedé con el pelo como nunca. Muy profesional, me explicó todo el proceso y me dijo cómo cuidarlo en casa. ¡Gracias!"',
    t2_service: 'Tratamiento Capilar',
    t3_text:    '"Me hicieron el maquillaje para mi grado y quedé preciosa. Camila se tomó el tiempo de entender el look que quería sin apresurarse. El resultado superó todas mis expectativas. ¡Mis fotos quedaron increíbles!"',
    t3_service: 'Maquillaje Profesional',
    t4_text:    '"Llevo tres años viniendo y no cambio Lumière por nada. Siempre me tratan con calor, el espacio es hermoso y los resultados son constantes. Es mi lugar de confianza en Medellín. ¡Las quiero mucho!"',
    t4_service: 'Clienta frecuente',

    gallery_label:   'Nuestro trabajo',
    gallery_title_1: 'Galería',
    gallery_title_2: 'de transformaciones',
    gl1: 'Corte & Estilizado',
    gl2: 'Coloración',
    gl3: 'Nail Art',
    gl4: 'Maquillaje',
    gl5: 'Tratamientos',
    gl6: 'Cejas & Pestañas',

    book_label:   'Agendá tu cita',
    book_title_1: '¿Lista para',
    book_title_2: 'tu transformación?',
    book_desc:    'Escribinos por WhatsApp y te confirmamos la cita en menos de una hora. También podés completar el formulario y te contactamos nosotras.',
    book_wa:      'Escríbenos por WhatsApp',
    book_or:      'O llámanos:',

    form_title:               'Reservar cita',
    form_name:                'Tu nombre',
    form_name_placeholder:    'Ej: Laura Gómez',
    form_service:             'Servicio',
    form_service_placeholder: 'Selecciona un servicio',
    form_date:                'Fecha',
    form_time:                'Hora',
    form_time_placeholder:    'Selecciona hora',
    form_submit:              'Confirmar reserva',
    err_name:    'Por favor ingresa tu nombre.',
    err_service: 'Por favor selecciona un servicio.',
    err_date:    'Selecciona una fecha.',
    err_time:    'Selecciona una hora.',

    confirm_title: '¡Cita enviada!',
    confirm_text:  'Te redirigimos a WhatsApp para confirmar tu cita. ¡Nos vemos pronto! 🌸',

    footer_tagline:      'Tu espacio de belleza y bienestar en el corazón de Medellín. Donde cada detalle importa.',
    footer_links:        'Links',
    footer_contact:      'Contacto',
    footer_address_html: 'Calle 10 # 43E-40, El Poblado<br>Medellín, Antioquia',
    footer_hours_html:   'Mar – Sáb: 9am – 7pm<br>Dom: 10am – 4pm',
    footer_copy:         `© ${new Date().getFullYear()} Lumière Studio. Todos los derechos reservados.`,
    footer_made:         'Hecho con amor en Medellín 🌸',

    wa_tooltip: 'Escríbenos',
  },

  en: {
    nav_servicios:  'Services',
    nav_nosotras:   'About',
    nav_equipo:     'Team',
    nav_opiniones:  'Reviews',
    nav_galeria:    'Gallery',
    nav_cta:        'Book Now',

    hero_eyebrow:    'Premium Beauty Salon · Medellín',
    hero_title_1:    'Your beauty,',
    hero_title_2:    'our passion',
    hero_sub:        'An intimate space where every visit is a ritual. You arrive as a client, you leave feeling like the best version of yourself.',
    hero_badge:      'Available today',
    hero_float_main: '4.9 on Google',
    hero_float_sub:  '+400 reviews',
    cta_reservar:    'Book now',
    cta_servicios:   'Our services',

    trust_1_bold: '4.9★ on Google',
    trust_2:      '4,000+ happy clients',
    trust_3:      '6 years in Medellín',
    trust_4:      'Cruelty-free products',

    services_label:   'Our services',
    services_title_1: 'What we do',
    services_title_2: 'for you',
    services_desc:    'Every service is crafted with care, using premium products and the latest techniques.',

    s1_name:  'Cut & Styling',
    s1_price: '$45,000 – $80,000 COP',
    s1_desc:  'Personalized cut tailored to your face shape and style, including professional blow-dry and finish.',
    s2_name:  'Color & Highlights',
    s2_price: '$120,000 – $250,000 COP',
    s2_desc:  'Full color, balayage, highlights, and color techniques perfectly adapted to your hair.',
    s3_name:  'Hair Treatments',
    s3_price: '$60,000 – $150,000 COP',
    s3_desc:  'Keratin, deep hydration, and hair nutrition for soft, shiny, and healthy hair.',
    s4_name:  'Manicure & Pedicure',
    s4_price: '$35,000 – $65,000 COP',
    s4_desc:  'Complete hand and foot care with gel polish, nail art, and nail spa treatments.',
    s5_name:  'Professional Makeup',
    s5_price: '$80,000 – $120,000 COP',
    s5_desc:  'Social, evening, or special event makeup. Natural or glamorous — whatever you need.',
    s6_name:  'Brows & Lashes',
    s6_price: '$40,000 – $70,000 COP',
    s6_desc:  'Brow design and waxing, lamination, tinting, and lash extensions for a perfect gaze.',
    service_book: 'Book →',

    ritual_1: 'Every visit is your moment',
    ritual_2: 'Because you deserve to feel incredible every day',

    why_label:   'Why Lumière?',
    why_title_1: 'More than a salon,',
    why_title_2: 'an experience',
    why1_title:  'Personalized consultation',
    why1_desc:   'Before any service, we talk about what you want and what works best for your hair, skin, or style.',
    why2_title:  'Premium products',
    why2_desc:   'We only use high-end, cruelty-free brands with ingredients that genuinely care for your hair and skin.',
    why3_title:  'Intimate, relaxed setting',
    why3_desc:   'Our space was designed to make you feel at home: calm, comfortable, and completely at ease.',

    team_label:   'Meet the team',
    team_title_1: 'The artists',
    team_title_2: 'behind your look',
    team_desc:    'Passionate women, experts in their craft, dedicated to making every client leave happy.',
    t1_role: 'Lead Colorist & Stylist',
    t1_exp:  '10 years experience · Certified in Paris',
    t2_role: 'Hair Treatment Specialist',
    t2_exp:  '7 years experience · Keratin expert',
    t3_role: 'Nail Artist & Makeup Artist',
    t3_exp:  '5 years experience · Nail art specialist',

    testi_label:   'What they say',
    testi_title_1: 'Clients who',
    testi_title_2: 'found their glow',
    t1_text:    '"Valentina did the most beautiful balayage I\'ve ever seen. I told her exactly what I wanted and she nailed it. The salon atmosphere is super welcoming, nothing intimidating at all. Definitely coming back!"',
    t1_service: 'Color & Highlights',
    t2_text:    '"My hair had been damaged by heat for months. Daniela did a deep hydration treatment and my hair has never felt better. Very professional — she explained everything and told me how to care for it at home."',
    t2_service: 'Hair Treatment',
    t3_text:    '"They did my graduation makeup and I looked stunning. Camila took the time to understand the look I wanted without rushing. The result exceeded all my expectations. My photos turned out incredible!"',
    t3_service: 'Professional Makeup',
    t4_text:    '"I\'ve been coming for three years and I wouldn\'t trade Lumière for anything. They always treat me warmly, the space is beautiful, and the results are consistently amazing. My trusted spot in Medellín!"',
    t4_service: 'Loyal client',

    gallery_label:   'Our work',
    gallery_title_1: 'Gallery',
    gallery_title_2: 'of transformations',
    gl1: 'Cut & Styling',
    gl2: 'Color',
    gl3: 'Nail Art',
    gl4: 'Makeup',
    gl5: 'Treatments',
    gl6: 'Brows & Lashes',

    book_label:   'Schedule your visit',
    book_title_1: 'Ready for',
    book_title_2: 'your transformation?',
    book_desc:    "Message us on WhatsApp and we'll confirm your appointment within the hour. Or fill out the form and we'll reach out to you.",
    book_wa:      'Message us on WhatsApp',
    book_or:      'Or call us:',

    form_title:               'Book appointment',
    form_name:                'Your name',
    form_name_placeholder:    'e.g. Laura Gómez',
    form_service:             'Service',
    form_service_placeholder: 'Select a service',
    form_date:                'Date',
    form_time:                'Time',
    form_time_placeholder:    'Select time',
    form_submit:              'Confirm booking',
    err_name:    'Please enter your name.',
    err_service: 'Please select a service.',
    err_date:    'Please select a date.',
    err_time:    'Please select a time.',

    confirm_title: 'Booking sent!',
    confirm_text:  "We're redirecting you to WhatsApp to confirm your appointment. See you soon! 🌸",

    footer_tagline:      'Your beauty and wellness space in the heart of Medellín. Where every detail matters.',
    footer_links:        'Links',
    footer_contact:      'Contact',
    footer_address_html: 'Calle 10 # 43E-40, El Poblado<br>Medellín, Antioquia',
    footer_hours_html:   'Tue – Sat: 9am – 7pm<br>Sun: 10am – 4pm',
    footer_copy:         `© ${new Date().getFullYear()} Lumière Studio. All rights reserved.`,
    footer_made:         'Made with love in Medellín 🌸',

    wa_tooltip: 'Message us',
  },
};
