'use strict';

const CONFIG = {
  WHATSAPP_NUMBER:         '573001234567',
  CAROUSEL_INTERVAL_MS:    5500,
  BACK_TOP_THRESHOLD_PX:   300,
  NAV_SCROLL_THRESHOLD_PX: 50,
  REVEAL_THRESHOLD: 0.1,
  STORAGE_KEY: 'lumiere_lang',
  DEFAULT_LANG: 'es',
  EASTER_EGG_WORD: 'belleza',
  PARTICLE_COUNT: 20,
};

const TRANSLATIONS = {
  es: {
    nav_servicios:  'Servicios',
    nav_nosotras:   'Nosotras',
    nav_equipo:     'Equipo',
    nav_opiniones:  'Opiniones',
    nav_galeria:    'Galería',
    nav_cta:        'Reservar',

    // Hero
    hero_eyebrow:    'Salón de belleza · Laureles, Medellín',
    hero_title_1:    'Acá el tiempo',
    hero_title_2:    'se toma con calma',
    hero_sub:        'Entrás con el día encima y el pelo cansado, y salís oliendo a aceite de argán, con el cabello liviano y la sensación de que alguien por fin te puso atención de verdad.',
    hero_badge:      'Disponible hoy',
    hero_float_main: '4.9 en Google',
    hero_float_sub:  '+400 reseñas',
    cta_reservar:    'Reservar ahora',
    cta_servicios:   'Ver servicios',

    // Trust bar
    trust_1_label: 'en Google',
    trust_2_label: 'clientas felices',
    trust_3_label: 'años en Medellín',
    trust_4:       'Productos libres de crueldad',

    services_label:   'Nuestros servicios',
    services_title_1: 'Lo que hacemos',
    services_title_2: 'para vos',
    services_desc:    'Cada servicio empieza con una conversación. De ahí salen los detalles que hacen la diferencia.',

    // Service filters
    filter_all:      'Todos',
    filter_cabello:  'Cabello',
    filter_unas:     'Uñas',
    filter_estetica: 'Estética',

    s1_name:  'Corte y Estilizado',
    s1_price: '$45.000 – $80.000 COP',
    s1_desc:  'Cortamos en seco primero, para ver cómo cae tu pelo de verdad antes de definir la línea. Salís con un corte que se peina solo, sin pelear con la plancha todas las mañanas.',
    s2_name:  'Coloración y Mechas',
    s2_price: '$120.000 – $250.000 COP',
    s2_desc:  'Hacemos siempre una prueba de mechón antes de aplicar el color, para que no haya sorpresas con el tono. El brillo dura semanas porque trabajamos con fórmulas que no resecan.',
    s3_name:  'Tratamientos Capilares',
    s3_price: '$60.000 – $150.000 COP',
    s3_desc:  'Si tu pelo quedó como paja después del verano o de tanta plancha, esto lo revive de raíz. Salís con el cabello suave al tacto y sin ese frizz que no hay forma de peinar.',
    s4_name:  'Manicure y Pedicure',
    s4_price: '$35.000 – $65.000 COP',
    s4_desc:  'Empezamos limando en seco para cuidar la cutícula, nada de cortes a lo bruto. El esmaltado semipermanente aguanta hasta tres semanas sin descascararse en las puntas.',
    s5_name:  'Maquillaje Profesional',
    s5_price: '$80.000 – $120.000 COP',
    s5_desc:  'Usamos bases que aguantan sudor, abrazos y flash de cámara sin sentirse pesadas. Te vas viéndote vos misma, solo que con mejor luz.',
    s6_name:  'Cejas y Pestañas',
    s6_price: '$40.000 – $70.000 COP',
    s6_desc:  'Diseñamos la forma según el hueso de tu ceja, no según una plantilla. Te cambia la mirada sin que se note que te hiciste algo.',
    service_book: 'Reservar →',

    // Ritual strips
    ritual_1: 'Acá nadie te apura — tu cita es tuya, de principio a fin.',
    ritual_2: 'Porque un buen corte te puede cambiar el ánimo de la semana entera.',

    why_label:   '¿Por qué Lumière?',
    why_title_1: 'Más que un salón,',
    why_title_2: 'una experiencia',
    why1_title:  'Antes de tocarte el pelo, hablamos',
    why1_desc:   'Nos sentamos con vos, te preguntamos qué te gustó y qué no de tu último corte, y de ahí armamos el plan juntas. Nada de sorpresas cuando ya es tarde para cambiar de opinión.',
    why2_title:  'Lo que usamos en vos, lo usamos en nosotras',
    why2_desc:   'Trabajamos con líneas profesionales libres de crueldad animal — del nivel de Olaplex y Kérastase. Tu cabello y tu piel lo notan desde la primera sesión.',
    why3_title:  'Un espacio que no se siente sala de espera',
    why3_desc:   'Somos pocas sillas, música bajita y algo calientico mientras esperás. Nada de filas ni de sentirte un número más en la agenda.',

    team_label:   'Conocé al equipo',
    team_title_1: 'Las artistas',
    team_title_2: 'detrás de tu look',
    team_desc:    'Mujeres apasionadas, expertas en su arte y con ganas de hacer que cada clienta salga feliz.',
    t1_role: 'Colorista & Estilista Jefe',
    t1_exp:  '10 años de experiencia · Certificada en París',
    t2_role: 'Especialista en Tratamientos',
    t2_exp:  '7 años de experiencia · Experta en queratina',
    t3_role: 'Nail Artist & Maquilladora',
    t3_exp:  '5 años de experiencia · Especialista en nail art',

    testi_label:   'Lo que dicen ellas',
    testi_title_1: 'Clientas que',
    testi_title_2: 'volvieron a brillar',
    testi_rating_score: '4.9',
    testi_rating_text:  'basado en +400 reseñas de Google',
    t1_text:    '"Le mostré una foto de Pinterest a Valentina y le dije: algo así, pero que no se vea forzado. Me hizo un balayage que parece que el sol me lo hubiera pintado. Llevo meses recibiendo cumplidos y todavía no necesito retoque."',
    t1_service: 'Coloración y Mechas',
    t2_text:    '"Tenía el pelo frito de tanta plancha y ya ni sabía qué hacer con él. Daniela me hizo el tratamiento de keratina y quedé que ni yo me lo creía: se seca solo y queda liso sin necesidad de plancharlo. Vale cada peso."',
    t2_service: 'Tratamiento Capilar',
    t3_text:    '"Fui para el maquillaje de grado de mi hija con los nervios en el cuello. Camila me preguntó cuánto maquillaje uso normalmente y me dejó natural pero con un brillo que se notó hasta en las fotos. Lloré, pero de la buena."',
    t3_service: 'Maquillaje Profesional',
    t4_text:    '"Vivo en Belén pero igual cojo bus hasta Laureles, porque acá sí me conocen: saben que no me gusta el agua muy caliente en el lavado y que prefiero las uñas cortas. Esos detalles son los que a una la hacen volver."',
    t4_service: 'Clienta frecuente',

    gallery_label:   'Nuestro trabajo',
    gallery_title_1: 'Galería',
    gallery_title_2: 'de transformaciones',
    gl1: 'Interior del salón',
    gl2: 'Coloración y mechas',
    gl3: 'Corte y Estilizado',
    gl4: 'Manicure y Nail Art',
    gl5: 'Estilizado profesional',
    gl6: 'Brushing y secado',

    book_label:   'Agendá tu cita',
    book_title_1: 'Separá tu',
    book_title_2: 'espacio acá',
    book_desc:    'Mandanos un mensaje por WhatsApp con el día y la hora que te quede mejor, y te confirmamos en menos de una hora. Si preferís, llená el formulario y nosotras te escribimos.',
    book_wa:      'Escríbenos por WhatsApp',
    book_or:      'O llámanos:',

    // Form / step indicator
    step_1: 'Datos',
    step_2: 'Servicio',
    step_3: 'Confirmar',
    form_title:               'Reservar cita',
    form_name:                'Tu nombre',
    form_name_placeholder:    'Ej: Laura Gómez',
    form_service:             'Servicio',
    form_service_placeholder: 'Selecciona un servicio',
    form_date:                'Fecha',
    form_time:                'Hora',
    form_time_placeholder:    'Selecciona hora',
    form_next:                'Siguiente',
    form_back:                'Atrás',
    form_submit:              'Confirmar reserva',
    err_name:    'Por favor ingresa tu nombre.',
    err_service: 'Por favor selecciona un servicio.',
    err_date:    'Selecciona una fecha.',
    err_time:    'Selecciona una hora.',

    confirm_title: '¡Cita enviada!',
    confirm_text:  'Te redirigimos a WhatsApp para confirmar tu cita. ¡Nos vemos pronto! 🌸',

    // Footer
    footer_tagline: 'A cinco cuadras del parque de Laureles, con la puerta abierta de martes a sábado. Vení y tomate un café mientras te consentimos.',
    footer_links:   'Links',
    footer_contact: 'Contacto',
    footer_address_html: 'Carrera 70 # 44A-23, Laureles<br>Medellín, Antioquia',
    footer_hours_html:   'Mar – Sáb: 9am – 7pm<br>Dom: 10am – 4pm',
    footer_copy:         `© ${new Date().getFullYear()} Lumière Studio. Todos los derechos reservados.`,
    footer_made:         'Hecho con amor en Medellín 🌸',

    wa_tooltip: 'Escríbenos',

    // Lightbox
    lightbox_close: 'Cerrar',
    lightbox_prev:  'Imagen anterior',
    lightbox_next:  'Imagen siguiente',
  },

  en: {
    nav_servicios:  'Services',
    nav_nosotras:   'About',
    nav_equipo:     'Team',
    nav_opiniones:  'Reviews',
    nav_galeria:    'Gallery',
    nav_cta:        'Book Now',

    // Hero
    hero_eyebrow:    'Beauty salon · Laureles, Medellín',
    hero_title_1:    'Around here, time',
    hero_title_2:    'slows down',
    hero_sub:        'You walk in carrying the whole day, and you walk out smelling of argan oil, with lighter hair and the feeling that someone finally paid real attention to you.',
    hero_badge:      'Available today',
    hero_float_main: '4.9 on Google',
    hero_float_sub:  '+400 reviews',
    cta_reservar:    'Book now',
    cta_servicios:   'Our services',

    // Trust bar
    trust_1_label: 'on Google',
    trust_2_label: 'happy clients',
    trust_3_label: 'years in Medellín',
    trust_4:       'Cruelty-free products',

    services_label:   'Our services',
    services_title_1: 'What we do',
    services_title_2: 'for you',
    services_desc:    'Every service starts with a conversation. That\'s where the details that make the difference come from.',

    // Service filters
    filter_all:      'All',
    filter_cabello:  'Hair',
    filter_unas:     'Nails',
    filter_estetica: 'Beauty',

    s1_name:  'Cut & Styling',
    s1_price: '$45,000 – $80,000 COP',
    s1_desc:  'We cut on dry hair first, to see how it really falls before shaping the line. You leave with a cut that styles itself, no fighting the flat iron every morning.',
    s2_name:  'Color & Highlights',
    s2_price: '$120,000 – $250,000 COP',
    s2_desc:  'We always run a strand test before applying any color, so there are no surprises with the tone. The shine lasts for weeks because we use formulas that don\'t dry out your hair.',
    s3_name:  'Hair Treatments',
    s3_price: '$60,000 – $150,000 COP',
    s3_desc:  'If your hair feels like straw after summer or too much heat styling, this brings it back to life from the root. You leave with soft hair and none of that frizz you can\'t tame.',
    s4_name:  'Manicure & Pedicure',
    s4_price: '$35,000 – $65,000 COP',
    s4_desc:  'We start by dry-filing to protect the cuticle, never rough cutting. The gel polish holds up to three weeks without chipping at the tips.',
    s5_name:  'Professional Makeup',
    s5_price: '$80,000 – $120,000 COP',
    s5_desc:  'We use bases that hold up to sweat, hugs, and camera flash without feeling heavy. You leave looking like yourself, just with better lighting.',
    s6_name:  'Brows & Lashes',
    s6_price: '$40,000 – $70,000 COP',
    s6_desc:  'We design the shape around your own brow bone, not a template. It changes your whole look without anyone noticing you had work done.',
    service_book: 'Book →',

    // Ritual strips
    ritual_1: 'No one rushes you here — your appointment is yours, start to finish.',
    ritual_2: 'Because a good haircut can change the mood of your whole week.',

    why_label:   'Why Lumière?',
    why_title_1: 'More than a salon,',
    why_title_2: 'an experience',
    why1_title:  'Before we touch your hair, we talk',
    why1_desc:   'We sit down with you, ask what you liked and didn\'t about your last cut, and build the plan together from there. No surprises once it\'s too late to change your mind.',
    why2_title:  'What we use on you, we use on ourselves',
    why2_desc:   'We work with cruelty-free professional lines — Olaplex and Kérastase level. Your hair and skin notice from the very first session.',
    why3_title:  'A space that doesn\'t feel like a waiting room',
    why3_desc:   'A handful of chairs, low music, and something warm to drink while you wait. No lines, no feeling like just another slot in the schedule.',

    team_label:   'Meet the team',
    team_title_1: 'The artists',
    team_title_2: 'behind your look',
    team_desc:    'Passionate women, experts in their craft, dedicated to making every client leave happy.',
    t1_role: 'Lead Colorist & Stylist',
    t1_exp:  '10 years experience · Certified in Paris',
    t2_role: 'Hair Treatment Specialist',
    t2_exp:  '7 years experience · Keratin expert',
    t3_role: 'Nail Artist & Makeup Artist',
    t3_exp:  '5 years experience · Nail art specialist',

    testi_label:   'What they say',
    testi_title_1: 'Clients who',
    testi_title_2: 'found their glow',
    testi_rating_score: '4.9',
    testi_rating_text:  'based on 400+ Google reviews',
    t1_text:    '"I showed Valentina a photo from Pinterest and said: something like this, but not too obvious. She did a balayage that looks like the sun painted it. I\'ve been getting compliments for months and still don\'t need a touch-up."',
    t1_service: 'Color & Highlights',
    t2_text:    '"My hair was fried from too much heat styling and I didn\'t know what to do with it anymore. Daniela did the keratin treatment and I couldn\'t believe it — it air-dries straight, no flat iron needed. Worth every peso."',
    t2_service: 'Hair Treatment',
    t3_text:    '"I came in for my daughter\'s graduation makeup, nerves and all. Camila asked how much makeup I usually wear and kept it natural but with a glow that showed up in every photo. I cried — the good kind."',
    t3_service: 'Professional Makeup',
    t4_text:    '"I live across town but I still take the bus to Laureles, because here they actually know me — they know I don\'t like the water too hot during a wash and that I keep my nails short. Little things like that are what bring you back."',
    t4_service: 'Loyal client',

    gallery_label:   'Our work',
    gallery_title_1: 'Gallery',
    gallery_title_2: 'of transformations',
    gl1: 'Salon interior',
    gl2: 'Color and highlights',
    gl3: 'Cut and styling',
    gl4: 'Manicure and nail art',
    gl5: 'Professional styling',
    gl6: 'Blow-dry finish',

    // Booking
    book_label:   'Book your visit',
    book_title_1: 'Save your',
    book_title_2: 'spot here',
    book_desc:    'Send us a WhatsApp message with the day and time that works best for you, and we\'ll confirm within the hour. Or fill out the form and we\'ll reach out to you.',
    book_wa:      'Message us on WhatsApp',
    book_or:      'Or call us:',

    // Form / step indicator
    step_1: 'Details',
    step_2: 'Service',
    step_3: 'Confirm',
    form_title:               'Book appointment',
    form_name:                'Your name',
    form_name_placeholder:    'e.g. Laura Gómez',
    form_service:             'Service',
    form_service_placeholder: 'Select a service',
    form_date:                'Date',
    form_time:                'Time',
    form_time_placeholder:    'Select time',
    form_next:                'Next',
    form_back:                'Back',
    form_submit:              'Confirm booking',
    err_name:    'Please enter your name.',
    err_service: 'Please select a service.',
    err_date:    'Please select a date.',
    err_time:    'Please select a time.',

    confirm_title: 'Booking sent!',
    confirm_text:  "We're redirecting you to WhatsApp to confirm your appointment. See you soon! 🌸",

    // Footer
    footer_tagline: 'Five blocks from Parque de Laureles, doors open Tuesday through Saturday. Come in and have a coffee while we take care of you.',
    footer_links:   'Links',
    footer_contact: 'Contact',
    footer_address_html: 'Carrera 70 # 44A-23, Laureles<br>Medellín, Antioquia',
    footer_hours_html:   'Tue – Sat: 9am – 7pm<br>Sun: 10am – 4pm',
    footer_copy:         `© ${new Date().getFullYear()} Lumière Studio. All rights reserved.`,
    footer_made:         'Made with love in Medellín 🌸',

    wa_tooltip: 'Message us',

    // Lightbox
    lightbox_close: 'Close',
    lightbox_prev:  'Previous image',
    lightbox_next:  'Next image',
  },
};
